### ISSUE TITLE
cannot compile 

### ISSUE THREAD

**Issue by junkandshit** [salvatoreBosco/KWP2000_arduino#1]
when try to compile i get this errror 
"C:\TEMP\cc8v24p6.ltrans0.ltrans.o: In function `loop':
C:\TEMP\arduino_modified_sketch_6655/SimpleTest.ino:47: undefined reference to `kwp::request(int, char)'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Nano."

**Comment by salvatoreBosco** [comment]
> when try to compile i get this errror "C:\TEMP\cc8v24p6.ltrans0.ltrans.o: In function `loop': C:\TEMP\arduino_modified_sketch_6655/SimpleTest.ino:47: undefined reference to `kwp::request(int, char)' collect2.exe: error: ld returned 1 exit status exit status 1 Error compiling for board Arduino Nano."

Thanks for your feedback. 

The project was developed with an Arduino Uno. 
I don't have a chance to try a Nano. 

So i ask you to check if the problem is only for Arduino Nano by loading the sketch in an Arduino Uno if you have one.

let me know if it works.

**Comment by junkandshit** [comment]
the same. 
C:\TEMP\ccYi43Uv.ltrans0.ltrans.o: In function `loop':
C:\Users\M\Desktop\KWP2000_arduino-main\KWP2000_send_message_working\example\SimpleTest/SimpleTest.ino:47: undefined reference to `kwp::request(int, char)'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Uno.

i am using arduino 1.8.19 version.

**Comment by salvatoreBosco** [comment]
> the same. C:\TEMP\ccYi43Uv.ltrans0.ltrans.o: In function `loop': C:\Users\M\Desktop\KWP2000_arduino-main\KWP2000_send_message_working\example\SimpleTest/SimpleTest.ino:47: undefined reference to `kwp::request(int, char)' collect2.exe: error: ld returned 1 exit status exit status 1 Error compiling for board Arduino Uno.
> 
> i am using arduino 1.8.19 version.

I tried to see if it worked with other computers and they all matched perfectly. 

Another test you could do is: 

1. Delete my library directly in your computer's file explorer usually located at Documents / Arduino / libraries.  
2. Download the library with the zip format from github 
3. Add it to the other aruino libraries via zip (Sketch / #include library / add library from zip file
4. It may be necessary to close and reopen the Arduino IDE

Let me know if it works.

**Comment by junkandshit** [comment]
Yes it was my fault, it was old library in Documents / Arduino / libraries that caused  issue. Thanks for help!

**Comment by salvatoreBosco** [comment]
> Yes it was my fault, it was old library in Documents / Arduino / libraries that caused issue. Thanks for help!

Glad you managed to solve the problem! The code is constantly evolving so it can happen. 

I hope to finish completing all PIDs and services to offer a complete library.
